import { describe, expect, it, vi } from "vitest";
import {
  downloadYouTubeSubtitles,
  extractYouTubeVideoId,
} from "../youtube-subtitles.js";

function makeResponse(status: number, body: unknown, statusText = "") {
  return {
    ok: status >= 200 && status < 300,
    status,
    statusText,
    text: async () => (typeof body === "string" ? body : JSON.stringify(body)),
  };
}

function playerHtml(captionTracks: unknown[]) {
  return `<html><script>var ytInitialPlayerResponse = ${JSON.stringify({
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks,
      },
    },
  })};</script></html>`;
}

describe("extractYouTubeVideoId", () => {
  it("accepts a raw YouTube video ID", () => {
    expect(extractYouTubeVideoId("abc123DEF45")).toBe("abc123DEF45");
  });

  it("extracts IDs from common YouTube URL shapes", () => {
    expect(extractYouTubeVideoId("https://www.youtube.com/watch?v=abc123DEF45")).toBe("abc123DEF45");
    expect(extractYouTubeVideoId("https://youtu.be/abc123DEF45")).toBe("abc123DEF45");
    expect(extractYouTubeVideoId("https://www.youtube.com/shorts/abc123DEF45")).toBe("abc123DEF45");
    expect(extractYouTubeVideoId("https://www.youtube.com/embed/abc123DEF45")).toBe("abc123DEF45");
  });

  it("rejects invalid input", () => {
    expect(() => extractYouTubeVideoId("not a url")).toThrow(
      "Expected a YouTube video URL or 11-character video ID.",
    );
  });
});

describe("downloadYouTubeSubtitles", () => {
  it("fetches the English manual track by default and parses json3 cues", async () => {
    const fetch = vi
      .fn()
      .mockResolvedValueOnce(
        makeResponse(
          200,
          playerHtml([
            {
              baseUrl: "https://www.youtube.com/api/timedtext?v=abc123DEF45&lang=fr",
              languageCode: "fr",
              name: { simpleText: "French" },
            },
            {
              baseUrl: "https://www.youtube.com/api/timedtext?v=abc123DEF45&lang=en",
              languageCode: "en",
              name: { simpleText: "English" },
              isTranslatable: true,
            },
          ]),
        ),
      )
      .mockResolvedValueOnce(
        makeResponse(200, {
          events: [
            {
              tStartMs: 0,
              dDurationMs: 1200,
              segs: [{ utf8: "Hello" }, { utf8: " world" }],
            },
            {
              tStartMs: 1300,
              dDurationMs: 900,
              segs: [{ utf8: "Next line" }],
            },
          ],
        }),
      ) as unknown as typeof globalThis.fetch;

    const result = await downloadYouTubeSubtitles({
      videoIdOrUrl: "https://www.youtube.com/watch?v=abc123DEF45",
      fetch,
    });

    expect(result).toMatchObject({
      videoId: "abc123DEF45",
      languageCode: "en",
      languageName: "English",
      isAutoGenerated: false,
      isTranslatable: true,
      text: "Hello world\nNext line",
    });
    expect(result.cues).toEqual([
      { startMs: 0, durationMs: 1200, text: "Hello world" },
      { startMs: 1300, durationMs: 900, text: "Next line" },
    ]);

    const subtitlesUrl = new URL(String(vi.mocked(fetch).mock.calls[1]![0]));
    expect(subtitlesUrl.searchParams.get("fmt")).toBe("json3");
  });

  it("can prefer auto-generated captions for a requested language", async () => {
    const fetch = vi
      .fn()
      .mockResolvedValueOnce(
        makeResponse(
          200,
          playerHtml([
            {
              baseUrl: "https://www.youtube.com/api/timedtext?v=abc123DEF45&lang=en",
              languageCode: "en",
              name: { simpleText: "English" },
            },
            {
              baseUrl: "https://www.youtube.com/api/timedtext?v=abc123DEF45&lang=en&kind=asr",
              languageCode: "en",
              name: { simpleText: "English (auto-generated)" },
              kind: "asr",
            },
          ]),
        ),
      )
      .mockResolvedValueOnce(
        makeResponse(200, {
          events: [{ tStartMs: 0, dDurationMs: 1000, segs: [{ utf8: "Auto" }] }],
        }),
      ) as unknown as typeof globalThis.fetch;

    const result = await downloadYouTubeSubtitles({
      videoIdOrUrl: "abc123DEF45",
      languageCode: "en-US",
      preferAutoGenerated: true,
      fetch,
    });

    expect(result.languageName).toBe("English (auto-generated)");
    expect(result.isAutoGenerated).toBe(true);
  });

  it("reports available languages when the requested language is missing", async () => {
    const fetch = vi.fn().mockResolvedValueOnce(
      makeResponse(
        200,
        playerHtml([
          {
            baseUrl: "https://www.youtube.com/api/timedtext?v=abc123DEF45&lang=fr",
            languageCode: "fr",
            name: { simpleText: "French" },
          },
        ]),
      ),
    ) as unknown as typeof globalThis.fetch;

    await expect(
      downloadYouTubeSubtitles({
        videoIdOrUrl: "abc123DEF45",
        languageCode: "en",
        fetch,
      }),
    ).rejects.toThrow('No subtitles found for language "en". Available languages: fr (French).');
  });

  it("rejects unexpected caption hosts", async () => {
    const fetch = vi.fn().mockResolvedValueOnce(
      makeResponse(
        200,
        playerHtml([
          {
            baseUrl: "https://example.com/api/timedtext?v=abc123DEF45&lang=en",
            languageCode: "en",
            name: { simpleText: "English" },
          },
        ]),
      ),
    ) as unknown as typeof globalThis.fetch;

    await expect(
      downloadYouTubeSubtitles({
        videoIdOrUrl: "abc123DEF45",
        fetch,
      }),
    ).rejects.toThrow("unexpected caption URL");
  });
});
