import { z } from "zod";

const YOUTUBE_VIDEO_ID_PATTERN = /^[A-Za-z0-9_-]{11}$/;

const CaptionNameSchema = z
  .object({
    simpleText: z.string().optional(),
    runs: z
      .array(
        z.object({
          text: z.string(),
        }),
      )
      .optional(),
  })
  .optional();

const CaptionTrackSchema = z.object({
  baseUrl: z.string(),
  languageCode: z.string(),
  name: CaptionNameSchema,
  kind: z.string().optional(),
  vssId: z.string().optional(),
  isTranslatable: z.boolean().optional(),
});

const PlayerResponseSchema = z.object({
  captions: z
    .object({
      playerCaptionsTracklistRenderer: z
        .object({
          captionTracks: z.array(CaptionTrackSchema).optional(),
        })
        .optional(),
    })
    .optional(),
});

const Json3TranscriptSchema = z.object({
  events: z
    .array(
      z.object({
        tStartMs: z.number().optional(),
        dDurationMs: z.number().optional(),
        segs: z
          .array(
            z.object({
              utf8: z.string().optional(),
            }),
          )
          .optional(),
      }),
    )
    .optional(),
});

type CaptionTrack = z.infer<typeof CaptionTrackSchema>;

export interface YouTubeSubtitleTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
}

export interface YouTubeSubtitleCue {
  startMs: number;
  durationMs: number;
  text: string;
}

export interface YouTubeSubtitlesResult {
  videoId: string;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
  cues: YouTubeSubtitleCue[];
  text: string;
  availableTracks: YouTubeSubtitleTrack[];
}

export interface DownloadYouTubeSubtitlesConfig {
  videoIdOrUrl: string;
  languageCode?: string;
  preferAutoGenerated?: boolean;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export async function downloadYouTubeSubtitles(
  config: DownloadYouTubeSubtitlesConfig,
): Promise<YouTubeSubtitlesResult> {
  const fetchImpl = config.fetch ?? globalThis.fetch;
  const videoId = extractYouTubeVideoId(config.videoIdOrUrl);
  const tracks = await fetchCaptionTracks({
    videoId,
    languageCode: config.languageCode,
    fetchImpl,
    signal: config.signal,
  });

  if (tracks.length === 0) {
    throw new Error(`No public subtitle tracks found for YouTube video ${videoId}.`);
  }

  const track = selectCaptionTrack(
    tracks,
    config.languageCode,
    Boolean(config.preferAutoGenerated),
  );
  const cues = await fetchCaptionCues(track, fetchImpl, config.signal);
  const trackMeta = toPublicTrack(track);

  return {
    videoId,
    languageCode: trackMeta.languageCode,
    languageName: trackMeta.languageName,
    isAutoGenerated: trackMeta.isAutoGenerated,
    isTranslatable: trackMeta.isTranslatable,
    cues,
    text: cues.map((cue) => cue.text).join("\n"),
    availableTracks: tracks.map(toPublicTrack),
  };
}

export function extractYouTubeVideoId(input: string): string {
  const trimmed = input.trim();
  if (YOUTUBE_VIDEO_ID_PATTERN.test(trimmed)) return trimmed;

  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    throw new Error("Expected a YouTube video URL or 11-character video ID.");
  }

  const hostname = url.hostname.toLowerCase().replace(/^www\./, "");
  if (hostname === "youtu.be") {
    const id = url.pathname.split("/").filter(Boolean)[0] ?? "";
    if (YOUTUBE_VIDEO_ID_PATTERN.test(id)) return id;
  }

  if (hostname === "youtube.com" || hostname === "m.youtube.com") {
    const watchId = url.searchParams.get("v") ?? "";
    if (YOUTUBE_VIDEO_ID_PATTERN.test(watchId)) return watchId;

    const [first, second] = url.pathname.split("/").filter(Boolean);
    if (
      ["embed", "shorts", "live"].includes(first ?? "") &&
      second &&
      YOUTUBE_VIDEO_ID_PATTERN.test(second)
    ) {
      return second;
    }
  }

  throw new Error("Expected a YouTube video URL or 11-character video ID.");
}

async function fetchCaptionTracks({
  videoId,
  languageCode,
  fetchImpl,
  signal,
}: {
  videoId: string;
  languageCode?: string;
  fetchImpl: typeof globalThis.fetch;
  signal?: AbortSignal;
}) {
  const url = new URL("https://www.youtube.com/watch");
  url.searchParams.set("v", videoId);
  url.searchParams.set("hl", languageCode?.trim() || "en");

  const response = await fetchImpl(url.toString(), {
    headers: {
      accept: "text/html,*/*",
    },
    signal,
  });

  if (!response.ok) {
    throw new Error(
      `YouTube video page failed with HTTP ${response.status}${response.statusText ? ` ${response.statusText}` : ""}.`,
    );
  }

  const html = await response.text();
  const playerResponse = extractYtInitialPlayerResponse(html);
  const parsed = PlayerResponseSchema.safeParse(playerResponse);
  if (!parsed.success) {
    throw new Error("Could not parse YouTube player caption metadata.");
  }

  return (
    parsed.data.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
  );
}

function extractYtInitialPlayerResponse(html: string): unknown {
  const marker = "ytInitialPlayerResponse";
  let markerIndex = html.indexOf(marker);

  while (markerIndex >= 0) {
    const braceStart = html.indexOf("{", markerIndex + marker.length);
    if (braceStart < 0) break;

    const jsonText = readBalancedJsonObject(html, braceStart);
    if (jsonText) {
      try {
        return JSON.parse(jsonText) as unknown;
      } catch {
        // Keep looking in case another occurrence contains valid JSON.
      }
    }

    markerIndex = html.indexOf(marker, markerIndex + marker.length);
  }

  throw new Error("Could not find YouTube player metadata on the video page.");
}

function readBalancedJsonObject(input: string, start: number): string | null {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = start; index < input.length; index += 1) {
    const char = input[index];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
    } else if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;
      if (depth === 0) return input.slice(start, index + 1);
    }
  }

  return null;
}

function selectCaptionTrack(
  tracks: CaptionTrack[],
  languageCode: string | undefined,
  preferAutoGenerated: boolean,
) {
  const requestedLanguage = normalizeLanguageCode(languageCode);
  const candidates = requestedLanguage
    ? tracks.filter((track) =>
        languageMatches(track.languageCode, requestedLanguage),
      )
    : tracks;

  if (candidates.length === 0) {
    throw new Error(
      `No subtitles found for language "${languageCode}". Available languages: ${formatAvailableLanguages(tracks)}.`,
    );
  }

  if (!requestedLanguage) {
    const englishCandidates = candidates.filter((track) =>
      languageMatches(track.languageCode, "en"),
    );
    const englishPreferred = preferAutoGenerated
      ? englishCandidates.find(isAutoGeneratedTrack)
      : englishCandidates.find((track) => !isAutoGeneratedTrack(track));
    if (englishPreferred) return englishPreferred;
    if (englishCandidates[0]) return englishCandidates[0];
  }

  const preferred = preferAutoGenerated
    ? candidates.find(isAutoGeneratedTrack)
    : candidates.find((track) => !isAutoGeneratedTrack(track));
  if (preferred) return preferred;

  return candidates[0]!;
}

async function fetchCaptionCues(
  track: CaptionTrack,
  fetchImpl: typeof globalThis.fetch,
  signal?: AbortSignal,
): Promise<YouTubeSubtitleCue[]> {
  const url = new URL(track.baseUrl);
  assertYouTubeCaptionUrl(url);
  url.searchParams.set("fmt", "json3");

  const response = await fetchImpl(url.toString(), {
    headers: {
      accept: "application/json,text/plain,*/*",
    },
    signal,
  });

  if (!response.ok) {
    throw new Error(
      `YouTube subtitles failed with HTTP ${response.status}${response.statusText ? ` ${response.statusText}` : ""}.`,
    );
  }

  const text = await response.text();
  if (!text.trim()) {
    throw new Error(
      "YouTube returned an empty subtitle response. This video may require YouTube's proof-of-origin token.",
    );
  }

  let json: unknown;
  try {
    json = JSON.parse(text) as unknown;
  } catch {
    throw new Error("YouTube subtitles response was not valid json3.");
  }

  const parsed = Json3TranscriptSchema.safeParse(json);
  if (!parsed.success) {
    throw new Error("YouTube subtitles response did not match json3 format.");
  }

  const cues =
    parsed.data.events?.flatMap((event) => {
      const cueText = (event.segs ?? [])
        .map((segment) => segment.utf8 ?? "")
        .join("")
        .replace(/\s+/g, " ")
        .trim();
      if (!cueText) return [];

      return [
        {
          startMs: event.tStartMs ?? 0,
          durationMs: event.dDurationMs ?? 0,
          text: cueText,
        },
      ];
    }) ?? [];

  if (cues.length === 0) {
    throw new Error("No subtitle cues found in YouTube subtitles response.");
  }

  return cues;
}

function assertYouTubeCaptionUrl(url: URL) {
  const hostname = url.hostname.toLowerCase();
  const allowedHosts = new Set(["www.youtube.com", "youtube.com", "m.youtube.com"]);
  if (!allowedHosts.has(hostname) || url.pathname !== "/api/timedtext") {
    throw new Error("YouTube caption metadata returned an unexpected caption URL.");
  }
}

function toPublicTrack(track: CaptionTrack): YouTubeSubtitleTrack {
  return {
    languageCode: track.languageCode,
    languageName: formatCaptionName(track.name) || track.languageCode,
    isAutoGenerated: isAutoGeneratedTrack(track),
    isTranslatable: Boolean(track.isTranslatable),
  };
}

function formatCaptionName(name: CaptionTrack["name"]) {
  if (!name) return "";
  if (name.simpleText) return name.simpleText;
  return (name.runs ?? []).map((run) => run.text).join("").trim();
}

function isAutoGeneratedTrack(track: CaptionTrack) {
  return track.kind === "asr" || track.vssId?.startsWith("a.") === true;
}

function normalizeLanguageCode(languageCode: string | undefined) {
  const trimmed = languageCode?.trim().toLowerCase();
  return trimmed || undefined;
}

function languageMatches(candidate: string, requested: string) {
  const normalizedCandidate = candidate.toLowerCase();
  return (
    normalizedCandidate === requested ||
    normalizedCandidate.startsWith(`${requested}-`) ||
    requested.startsWith(`${normalizedCandidate}-`)
  );
}

function formatAvailableLanguages(tracks: CaptionTrack[]) {
  return tracks
    .map((track) => {
      const name = formatCaptionName(track.name);
      return name ? `${track.languageCode} (${name})` : track.languageCode;
    })
    .join(", ");
}
