import { PageExtractor, type ExtractorInput, type ExtractorResult } from "./base.js";
import {
  downloadYouTubeSubtitles,
  extractYouTubeVideoId,
  type YouTubeSubtitlesResult,
} from "../../youtube-subtitles.js";

export interface YouTubeSubtitleDownloadInput {
  url: string;
  videoId: string;
  reason: string;
  signal?: AbortSignal;
}

export type YouTubeSubtitleDownloader = (
  input: YouTubeSubtitleDownloadInput,
) => Promise<YouTubeSubtitlesResult>;

export interface YouTubeExtractorConfig {
  subtitleDownloader?: YouTubeSubtitleDownloader;
}

export function isYouTubeVideoUrl(url: URL): boolean {
  try {
    extractYouTubeVideoId(url.href);
    return true;
  } catch {
    return false;
  }
}

export function formatYouTubeTranscript(
  subtitles: YouTubeSubtitlesResult,
  sourceUrl: string,
): string {
  const lines = [
    "# YouTube Transcript",
    "",
    `Source: ${sourceUrl}`,
    `Video ID: ${subtitles.videoId}`,
    `Language: ${subtitles.languageName} (${subtitles.languageCode})`,
    `Caption type: ${subtitles.isAutoGenerated ? "auto-generated" : "manual"}`,
  ];

  if (subtitles.availableTracks.length > 0) {
    lines.push(`Available tracks: ${formatAvailableTracks(subtitles)}`);
  }

  lines.push("", "## Transcript", "");
  for (const cue of subtitles.cues) {
    lines.push(`[${formatTimestamp(cue.startMs)}] ${cue.text}`);
  }

  return lines.join("\n");
}

export class YouTubeExtractor extends PageExtractor {
  constructor(private readonly config: YouTubeExtractorConfig = {}) {
    super();
  }

  canHandle(url: URL): boolean {
    return isYouTubeVideoUrl(url);
  }

  async extract(input: ExtractorInput): Promise<ExtractorResult | null> {
    try {
      const subtitles = await downloadYouTubeSubtitles({
        videoIdOrUrl: input.url.href,
        fetch: input.fetch ?? globalThis.fetch,
        signal: input.signal,
      });

      if (!subtitles.text.trim()) {
        return youtubeTranscriptUnavailableResult(
          input.url.href,
          "YouTube returned no subtitle text.",
        );
      }

      return {
        content: formatYouTubeTranscript(subtitles, input.url.href),
      };
    } catch (error) {
      if (isAbortError(error)) throw error;
      return this.extractWithSubtitleFallback(
        input,
        error instanceof Error ? error.message : String(error),
      );
    }
  }

  private async extractWithSubtitleFallback(
    input: ExtractorInput,
    reason: string,
  ): Promise<ExtractorResult> {
    const videoId = extractYouTubeVideoId(input.url.href);
    const downloader = this.config.subtitleDownloader;

    if (!downloader) {
      return youtubeTranscriptUnavailableResult(input.url.href, reason);
    }

    try {
      const subtitles = await downloader({
        url: input.url.href,
        videoId,
        reason,
        signal: input.signal,
      });

      if (!subtitles.text.trim()) {
        return youtubeTranscriptUnavailableResult(
          input.url.href,
          `${reason}; yt-dlp subtitle fallback returned no text.`,
        );
      }

      return {
        content: formatYouTubeTranscript(subtitles, input.url.href),
        warnings: [
          `Public YouTube caption extraction failed for ${input.url.href}: ${reason}`,
          "Used configured yt-dlp subtitle fallback.",
        ],
      };
    } catch (error) {
      if (isAbortError(error)) throw error;
      const subtitleError = error instanceof Error ? error.message : String(error);
      return youtubeTranscriptUnavailableResult(
        input.url.href,
        `${reason}; yt-dlp subtitle fallback failed: ${subtitleError}`,
      );
    }
  }
}

function youtubeTranscriptUnavailableResult(
  sourceUrl: string,
  reason: string,
): ExtractorResult {
  return {
    content: [
      "# YouTube Transcript Unavailable",
      "",
      `Source: ${sourceUrl}`,
      "",
      "No YouTube transcript could be extracted from public caption tracks.",
      "",
      `Reason: ${reason}`,
    ].join("\n"),
    warnings: [`YouTube transcript unavailable for ${sourceUrl}: ${reason}`],
  };
}

function isAbortError(error: unknown): boolean {
  return error instanceof Error && error.name === "AbortError";
}

function formatAvailableTracks(subtitles: YouTubeSubtitlesResult): string {
  return subtitles.availableTracks
    .map((track) => {
      const type = track.isAutoGenerated ? ", auto-generated" : "";
      return `${track.languageName} (${track.languageCode}${type})`;
    })
    .join("; ");
}

function formatTimestamp(ms: number): string {
  const totalSeconds = Math.max(0, Math.floor(ms / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const minuteText = String(minutes).padStart(2, "0");
  const secondText = String(seconds).padStart(2, "0");
  if (hours > 0) {
    return `${hours}:${minuteText}:${secondText}`;
  }
  return `${minuteText}:${secondText}`;
}
